language: c

cache:
  directories:
    - $HOME/travis-cache

os: linux
dist: xenial

arch:
  - amd64
  - arm64
  - s390x
  - ppc64le

addons:
  apt:
    update: true
    packages: build-essential

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: osx

script: ci/arm64-segfault-demo.sh

notifications:
  email: false
