language: c

cache:
  directories:
    - $HOME/travis-cache

os: linux
dist: xenial

arch:
  - amd64
  - arm64
  - s390x
  - ppc64le

addons:
  apt:
    update: true
    packages: build-essential gdb 

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: osx

before_install:
   - ulimit -c
   - ulimit -a -S
   - ulimit -a -H
   - cat /proc/sys/kernel/core_pattern
   - cat /etc/default/apport
   - service --status-all || true
   - initctl list || true

script: ci/arm64-segfault-demo.sh

notifications:
  email: false
